#!/bin/sh

PREFIX=$1

cd $PREFIX/joe-2.3
if [ $PWD != $PREFIX/joe-2.3 ]; then
	echo "Bailing... directory $PREFIX/joe-2.3 does not exist!"
	exit 1
fi
touch .$$bogus
if [ ! -f .$$bogus ]; then
	echo "Bailing... directory $PREFIX/joe-2.3 not writeable!"
	exit 1
fi
rm -f .$$bogus
echo "Configuring joe-2.3 for prefix ${PREFIX%%/src*}"
sed "s^@@@prefix@@@^${PREFIX%%/src*}^" < Makefile.rpp > Makefile
